/**
 *
 * $Id$
 */
package typhonql.validation;

import org.eclipse.emf.common.util.EList;

import typhonql.Query;

/**
 * A sample validator interface for {@link typhonql.Queries}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueriesValidator {
	boolean validate();

	boolean validateQueries(EList<Query> value);
}
