/**
 *
 * $Id$
 */
package typhonql.validation;

import org.eclipse.emf.common.util.EList;

import typhonql.Expr;

/**
 * A sample validator interface for {@link typhonql.Update}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UpdateValidator {
	boolean validate();

	boolean validateEid(String value);
	boolean validateVid(String value);
	boolean validateWhere(EList<Expr> value);
	boolean validateSet(EList<Expr> value);
}
