/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.typhonql.TyphonQLRuntimeModule;
import org.xtext.typhonql.TyphonQLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TyphonQLIdeSetup extends TyphonQLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TyphonQLRuntimeModule(), new TyphonQLIdeModule()));
	}
	
}
