apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentdatabase-deployment
spec:
  selector:
    matchLabels:
      app: documentdatabase-pod
  template:
    metadata:
      labels:
        app: documentdatabase-pod
    spec:
      volumes:
      - name: documentdatabasevolume
        persistentVolumeClaim:
      containers:
        - name: documentdatabase-container
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME 
              value: chooseUsername
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: choosePassword
          
          
          volumeMounts:
            - name: documentdatabasevolume
              mountPath: /data/db
---
kind: Service
apiVersion: v1
metadata:
  name: documentdatabase
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: documentdatabase-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relationaldatabase-deployment
spec:
  selector:
    matchLabels:
      app: relationaldatabase-pod
  template:
    metadata:
      labels:
        app: relationaldatabase-pod
    spec:
      volumes:
      - name: relationaldatabasevolume
        persistentVolumeClaim:
      containers:
        - name: relationaldatabase-container
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: choosePassword
          
          
          volumeMounts:
            - name: relationaldatabasevolume
              mountPath: /var/lib/mysql
---
kind: Service
apiVersion: v1
metadata:
  name: relationaldatabase
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: relationaldatabase-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polystore-mongo-deployment
spec:
  selector:
    matchLabels:
      app: polystore-mongo-pod
  template:
    metadata:
      labels:
        app: polystore-mongo-pod
    spec:
      containers:
        - name: polystore-mongo-container
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME 
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
          
          
          
          
---
kind: Service
apiVersion: v1
metadata:
  name: polystore-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: polystore-mongo-pod
---
kind: Job
apiVersion: batch/v1
metadata:
  name: insert-models
spec:
  template:
    spec:
      containers:
        - name: insert-models
          image: mongo:latest
          command: ["/bin/sh", "-c"]
          args:
          # wait for polystore-mongo to be ready
            - sleep 20; 
              mongo --host polystore-mongo --port 27017 -u admin -p admin admin --eval 'db.models.insert([{"_id":UUID(), "version":1, "initializedDatabases":false, "initializedConnections":true, "contents":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><typhonDL:DeploymentModel xmi:version=\"2.0\" xmlns:xmi=\"http://www.omg.org/XMI\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:typhonDL=\"http://www.typhon.org/dsls/xtext/TyphonDL\">  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"webshop.xmi\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"DocumentDatabase.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"RelationalDatabase.tdl\"/>  <guiMetaInformation xsi:type=\"typhonDL:Import\" relativePath=\"dbTypes.tdl\"/>  <elements xsi:type=\"typhonDL:ContainerType\" name=\"Docker\"/>  <elements xsi:type=\"typhonDL:ClusterType\" name=\"Kubernetes\"/>  <elements xsi:type=\"typhonDL:PlatformType\" name=\"localhost\"/>  <elements xsi:type=\"typhonDL:Platform\" name=\"platformName\" type=\"//@elements.2\">    <clusters name=\"clusterName\" type=\"//@elements.1\">      <applications name=\"Polystore\">        <containers name=\"documentdatabase\" type=\"//@elements.0\">          <deploys reference=\"//@elements.4\"/>          <uri value=\"documentdatabase:27017\"/>          <volumes>            <decls volumeName=\"documentdatabasevolume\" volumeType=\"persistentVolumeClaim\">              <volumePath value=\"/data/db\"/>            </decls>          </volumes>        </containers>        <containers name=\"relationaldatabase\" type=\"//@elements.0\">          <deploys reference=\"//@elements.5\"/>          <uri value=\"relationaldatabase:3306\"/>          <volumes>            <decls volumeName=\"relationaldatabasevolume\" volumeType=\"persistentVolumeClaim\">              <volumePath value=\"/var/lib/mysql\"/>            </decls>          </volumes>        </containers>        <containers name=\"polystore-mongo\" type=\"//@elements.0\">          <deploys reference=\"//@elements.8\"/>          <uri value=\"polystore-mongo:27017\"/>        </containers>        <containers name=\"typhon-polystore-service\" type=\"//@elements.0\">          <deploys reference=\"//@elements.9\"/>          <ports>            <key_values name=\"published\" value=\"30061\"/>            <key_values name=\"target\" value=\"8080\"/>          </ports>          <uri value=\"typhon-polystore-service:8080\"/>        </containers>        <containers name=\"polystore-ui\" type=\"//@elements.0\">          <deploys reference=\"//@elements.10\"/>          <depends_on reference=\"//@elements.3/@clusters.0/@applications.0/@containers.3\"/>          <ports>            <key_values name=\"published\" value=\"30075\"/>            <key_values name=\"target\" value=\"4200\"/>          </ports>          <uri value=\"polystore-ui:4200\"/>        </containers>        <containers name=\"typhonql-server\" type=\"//@elements.0\">          <deploys reference=\"//@elements.11\"/>          <resources limitMemory=\"2048M\" reservationCPU=\"0.5\" reservationMemory=\"2048M\"/>          <uri value=\"typhonql-server:7000\"/>          <properties xsi:type=\"typhonDL:Key_Values\" name=\"restart\" value=\"always\"/>        </containers>        <containers name=\"kafka\" type=\"//@elements.0\">          <deploys reference=\"//@elements.12\"/>          <uri value=\"typhon-cluster-kafka-bootstrap:9092\"/>        </containers>        <volumes>          <names>documentdatabasevolume</names>          <names>relationaldatabasevolume</names>        </volumes>      </applications>    </clusters>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"DocumentDatabase\" type=\"//@elements.6\">    <credentials username=\"chooseUsername\" password=\"choosePassword\"/>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"RelationalDatabase\" type=\"//@elements.7\">    <credentials username=\"root\" password=\"choosePassword\"/>  </elements>  <elements xsi:type=\"typhonDL:DBType\" name=\"Mongo\">    <image value=\"mongo:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:DBType\" name=\"MariaDB\">    <image value=\"mariadb:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:DB\" name=\"polystore_db\" type=\"//@elements.6\">    <credentials username=\"admin\" password=\"admin\"/>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_api\">    <image value=\"clms/typhon-polystore-api:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_ui\">    <image value=\"clms/typhon-polystore-ui:latest\"/>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"polystore_ql\">    <image value=\"swatengineering/typhonql-server\"/>    <environment>      <parameters name=\"TZ\" value=\"Europe/London\"/>    </environment>  </elements>  <elements xsi:type=\"typhonDL:Software\" name=\"Kafka\"/></typhonDL:DeploymentModel>", "type":"DL", "dateReceived":ISODate(), "_class":"com.clms.typhonapi.models.Model" }, {"_id":UUID(), "version":1, "initializedDatabases":false, "initializedConnections":false, "contents":"<?xml version=\"1.0\" encoding=\"ASCII\"?><typhonml:Model xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:typhonml=\"http://org.typhon.dsls.typhonml.sirius\">  <entities name=\"Feedback\">    <attributes xsi:type=\"typhonml:Attribute\" name=\"id\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"content\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <relations name=\"item\" type=\"//@entities.1\" cardinality=\"one\"/>  </entities>  <entities name=\"Item\">    <attributes xsi:type=\"typhonml:Attribute\" name=\"id\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"name\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"description\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <relations name=\"basketItems\" type=\"//@entities.2\" cardinality=\"zero_many\"/>    <relations name=\"feedback\" type=\"//@entities.0\" cardinality=\"zero_many\" opposite=\"//@entities.0/@relations.0\" isContainment=\"true\"/>  </entities>  <entities name=\"BasketItem\">    <attributes xsi:type=\"typhonml:Attribute\" name=\"id\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"product_date\">      <type xsi:type=\"typhonml:DatetimeType\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"totalAmount\">      <type xsi:type=\"typhonml:BigintType\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"paidWith\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <relations name=\"items\" type=\"//@entities.1\" cardinality=\"zero_many\" opposite=\"//@entities.2/@relations.0\"/>    <relations name=\"customers\" type=\"//@entities.3\" cardinality=\"one\" opposite=\"//@entities.3/@relations.0\"/>  </entities>  <entities name=\"Customer\">    <attributes xsi:type=\"typhonml:Attribute\" name=\"id\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"name\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"comments\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"paymentsDetails\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <relations name=\"basketItems\" type=\"//@entities.2\" cardinality=\"zero_many\"/>    <relations name=\"address\" type=\"//@entities.4\" cardinality=\"one\"/>  </entities>  <entities name=\"Address\">    <attributes xsi:type=\"typhonml:Attribute\" name=\"streetName\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"streetNumber\">      <type xsi:type=\"typhonml:BigintType\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"zipcode\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"city\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <attributes xsi:type=\"typhonml:Attribute\" name=\"country\">      <type xsi:type=\"typhonml:StringType\" maxSize=\"32\"/>    </attributes>    <relations name=\"customer\" type=\"//@entities.3\" cardinality=\"one\" opposite=\"//@entities.3/@relations.1\"/>  </entities>  <databases xsi:type=\"typhonml:RelationalDB\" name=\"RelationalDatabase\">    <tables name=\"BasketDB\" entity=\"//@entities.2\">      <indexSpec name=\"basketIndex\" attributes=\"//@entities.2/@attributes.0\"/>      <idSpec attributes=\"//@entities.2/@attributes.0\"/>    </tables>    <tables name=\"CustomerDB\" entity=\"//@entities.3\">      <indexSpec name=\"customerIndex\" attributes=\"//@entities.3/@attributes.1\"/>      <idSpec attributes=\"//@entities.3/@attributes.1\"/>    </tables>    <tables name=\"AddressDB\" entity=\"//@entities.4\"/>    <tables name=\"ItemDB\" entity=\"//@entities.1\">      <indexSpec name=\"itemIndex\" attributes=\"//@entities.1/@attributes.1\"/>      <idSpec attributes=\"//@entities.1/@attributes.1\"/>    </tables>  </databases>  <databases xsi:type=\"typhonml:DocumentDB\" name=\"DocumentDatabase\">    <collections name=\"FeedbackDB\" entity=\"//@entities.0\"/>  </databases></typhonml:Model>", "type":"ML", "dateReceived":ISODate(), "_class":"com.clms.typhonapi.models.Model" }]);';
      restartPolicy: Never
---
