version: '3.7'

services:
  reviews:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/choosePassword
      NEO4J_dbms_security_procedures_unrestricted: apoc.
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - type: volume
        source: reviewsvolume
        target: /data
  dwh:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: choosePassword
    volumes:
      - type: volume
        source: dwhvolume
        target: /var/lib/mysql
  polystore-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./models/:/docker-entrypoint-initdb.d
  typhon-polystore-service:
    image: clms/typhon-polystore-api:latest
    ports:
      - target: 8080
        published: 8080
    entrypoint:
      - wait-for-it
      - polystore-mongo:27017
      - -t
      - '60'
      - --
      - java
      - -cp
      - /app/resources:/app/classes:/app/libs/*
      - com.clms.typhonapi.Application
    restart: always
  polystore-ui:
    image: clms/typhon-polystore-ui:latest
    depends_on:
      - typhon-polystore-service
    ports:
      - target: 4200
        published: 4200
  typhonql-server:
    image: swatengineering/typhonql-server
    environment:
      TZ: Europe/London
    deploy:
      resources:
        limits:
          
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 2048M
    restart: always
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: OUTSIDE://:29092, INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092, INSIDE://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    ports:
      - target: 29092
        published: 29092
  authAll:
    image: zolotas4/typhon-analytics-auth-all
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
  taskmanager:
    image: universityofyork/typhon-analytics:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    depends_on:
      - jobmanager
    command: taskmanager
    expose:
      - 6121
      - 6122
  jobmanager:
    image: universityofyork/typhon-analytics:latest
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    ports:
      - target: 8081
        published: 8081
    command: jobmanager
    expose:
      - 6123

volumes:
  reviewsvolume:
  dwhvolume:

