/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.typhonql.ui.internal.TyphonqlActivator;

public class TyphonQLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TyphonqlActivator.getInstance().getInjector("org.xtext.typhonql.TyphonQL");
	}

}
