/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.typhonql.ui.internal.TyphonqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TyphonQLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TyphonqlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TyphonqlActivator activator = TyphonqlActivator.getInstance();
		return activator != null ? activator.getInjector(TyphonqlActivator.ORG_XTEXT_TYPHONQL_TYPHONQL) : null;
	}

}
