/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTyphonQLScopeProvider extends DelegatingScopeProvider {
}
