/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.typhonql.parser.antlr.internal.InternalTyphonQLParser;
import org.xtext.typhonql.services.TyphonQLGrammarAccess;

public class TyphonQLParser extends AbstractAntlrParser {

	@Inject
	private TyphonQLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTyphonQLParser createParser(XtextTokenStream stream) {
		return new InternalTyphonQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Queries";
	}

	public TyphonQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TyphonQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
