/*
 * generated by Xtext 2.20.0
 */
package org.xtext.typhonql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TyphonQLUiModule extends AbstractTyphonQLUiModule {

	public TyphonQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
